#include <windows.h>
#include <mmsystem.h>
#include <MinHook.h>
#include <iostream>
#include <vector>
#include <map>
#include <set>
#include <sstream>
#include <unordered_map>
#include <functional>
#include <intrin.h>
#include <algorithm>
//Header
#include "Log.h"
#include "Memory.h"
#include "InputHook.h"
#include "CrossMapping.h"
#include "keyboard.h"
#include "sdk/types.h"
#include "sdk/enums.h"
#include "NativeInvoker.h"
#include "sdk/nativeCaller.h"
#include "sdk/natives.h"
#include "MemTools.h"
#include "Hook.h"
#include "script.h"
#include "SubMenus.h"
#include "Menu.h"
#include "HotKey.h"