//菜单枚举
enum SubMenus {
    NOMENU,
    mainmenu,
    //玩家选项
    player_option,
    //玩家模型
    player_model_option,
    //动物和人物
    player_model_animal,
    //武器选项
    weapon_option,
    //传送选项
    teleport_option,
    //保护选项
    protect_option,
    //常规防御
    protect_general_option,
    //载具选项
    vehicle_option,
    //刷出菜单
    vehicle_spawn_option,
    //车辆子选项
    sub_vehicle_option,
    //恢复选项
    recovery_option,
    //杂项
    misc_option,
    //在线选项
    online_option,
    //在线玩家操作选项
    online_sub_option,
    //在线玩家友好功能
    online_peaceful_option,
    //恶意攻击选项
    online_griefing_option,
    //车辆刷出
    //名钻赌场豪劫
    diamond_dlc,
    //名钻赌场更新
    casinoHeist_dlc,
    //竞技场之战
    arenawar_DLC,
    //末日豪劫DLC
    doomsday_DLC,
    //摩托车
    motorcycles,
    //船
    boats,
    //商业车辆
    commercial,
    //小型轿车
    compacts,
    //轿跑车
    coupes,
    //自行车
    cycles,
    //警用
    emergency,
    //直升机
    helicopters,
    //工业车辆
    industrial,
    //军用车
    military,
    //肌肉车
    muscle,
    //越野车
    off_road,
    //飞机
    planes,
    //轿车
    sedans,
    //公共服务车
    services,
    //跑车
    sports,
    //经典跑车
    sports_classics,
    //超级跑车
    super,
    //SUV
    SUVs,
    //拖车
    trailer,
    //火车
    trains,
    //公共事业车
    utility,
    //货车
    vans,
    //走私大暴走DLC
    Smugglers_DLC,
    //军火霸业DLC
    Gunrunning_DLC,
    //南圣安地列斯超级系列赛
    south_sport_series,
    //崩溃防护
    protect_crash_option,
    //全部玩家
    all_player_option,
    //赌场
    //方案
    casino_scheme,
    //目标
    casino_target,
    //枪手
    casino_gun,
    //车手
    casino_driver,
    //黑客
    casino_hacker,
};